module.exports = {
    '/api/sign-in': require('./login/index.js'),
    '/api/sign-up': require('./register/index.js'),
    '/api/home': require('./home/index.js'),
    '/api/campaign-detail': require('./campaign/campaign_detail.js'),
    '/api/donation-by-account': require('./donation/donation_by_account.js'),
    '/api/admin/get-all-user': require('./admin/admin_get_all_user.js'),
    '/api/admin/get-all-charity': require('./admin/admin_get_all_charity.js'),
    '/api/admin/get-all-campaign': require('./admin/admin_get_all_campaign.js'),
    '/api/admin/get-all-donate': require('./admin/admin_get_all_donate.js'),
    '/api/campaign-create': require('./campaign/campaign_create.js'),
    '/api/campaign-add-commet' : require('./campaign/campaign_add_comment.js'),
    '/api/donation-create': require('./donation/donation_create.js'),
    '/api/campaign-list': require('./campaign/campaign_list.js'),
    '/api/campaign-news': require('./campaign/campaign_news.js'),
    '/api/campaign-news-add': require('./campaign/campaign_news_add.js'),
    '/api/charity-update': require('./charity/charity_update.js'),
    '/api/protected': require('./protected/index.js'),
    '/api/reset-password': require('./email/send_mail.js'),
    '/api/user-info': require('./user/user_info.js'),
    '/api/update-password': require('./user/update_password.js'),
    '/api/update-user-info': require('./user/update_user.js'),
    '/api/charity-info': require('./charity/charity_info.js'),
    '/api/campaign-delete': require('./campaign/campaign_delete.js'),
    '/api/campaign-update': require('./campaign/campaign_update.js'),
    '/api/get-news-update': require('./api-news/index.js'),
    '/api/admin/update-status-charity': require('./charity/charity_update_status.js'),
    '/api/admin/delete-account': require('./admin/admin_delete_account.js'),
    '/api/admin/update-donation': require('./donation/donation_update_status.js')
}